### PR TITLE
Fix/browser compatibility

### LINKED ISSUE #119: Add translate button to Hugo pages
@Lane and @pjsier as of this moment I have the "introduction" paragraph of Why Eviction Matters (on cms-dev / staging) set up for translation. (File is `content/why-eviction-matters/intro.es.md`.) I'll add more translated content asap, but I'm thinking this at least should be enough to test implementation of the toggle into the header, whenever you're able.

### PR DESCRIPTION
**Pull request by pjsier**
Progress on #139 and #141, closes #119. Fixes some pictorial menu issues on Safari 9, and moves to jQuery to avoid compatibility bugs. Implements the language toggle the same way as rankings where it's always in the header, since we don't need the space there

### CODE REVIEW

**Comment by james-minton** [comment]
@pjsier first thing that seems to be an issue is the focus state on links. I understand the utility for accessibility, but this kinda ruins the experience for me:

screen shot 2018-04-05 at 11 49 18 am

And generally for other links too, but especially here. Can we do this just for keyboard navigation but not activate it on click?

**Comment by pjsier** [comment]
I'll defer to @Lane on that. I was basing it off of the link styles in the map and rankings tools

**Comment by james-minton** [comment]
Cool. Is there anything else I should take particular note of?

**Comment by pjsier** [comment]
If the scroll functionality, menu, language selector, and pictorial menu look all good to you I think those are the main things I wanted another set of eyes on. And as long as nothing else seems broken in general

**Comment by pjsier** [comment]
One thing we can do to make some of those outlines look cleaner though is to convert padding to margin where possible (to avoid the extra space on the bottom):

screen shot 2018-04-05 at 11 01 21 am

**Comment by james-minton** [comment]
Yeah. Just TBH I don't think I can live with that outline in general, and Noele even less so, I suspect.

**Comment by james-minton** [comment]
Everything else seems good to me; language selection doesn't persist across pages yet, but I'm guessing that's coming later. I like how it stays in the header on mobile.

**Comment by pjsier** [comment]
Sounds good! Then this should be ready to merge. I changed that `padding-bottom` to `margin-bottom` since it makes more sense anyway even with a different approach. And yeah, it's still only showing up on pages that have some kind of translation. This should be good to merge!

**Comment by james-minton** [comment]
Ok does merging mean holding off on the focus state? I kinda don't want  NYT seeing that.

Also, by persisting, I mean the language selected (En / Es) persists when you go to other pages with translations.

**Comment by pjsier** [comment]
I'll comment out the `focusState` mixin for regular links for now while we work on an alternate treatment

**Comment by james-minton** [comment]
Perfect, thanks -- feel free to merge then

**Pull request merged**
