### PR TITLE
Update header and footer styles

### LINKED ISSUE #95: Merge in header and footer
I'm hoping to go ahead and get this done - would like to show some live previews soon and don't want the distraction of the old header and footer. @pjsier? Thanks!

### PR DESCRIPTION
**Pull request by pjsier**
Closes #95, pulling in styles from map repo

screen shot 2018-03-10 at 7 57 54 pm
screen shot 2018-03-10 at 7 58 00 pm
screen shot 2018-03-10 at 7 58 10 pm

### CODE REVIEW

**Comment by james-minton** [comment]
Thanks, Pat, looking good! Can we incorporate the shrinking header functionality as well?

**Comment by pjsier** [comment]
Yep! The latest commit has the shrinking header

**Comment by james-minton** [comment]
Thanks! One thing -- it seems like it's on a longer delay / transitions are a bit more awkward than on the map / rankings. See https://enhancement-header-footer--eviction-lab.netlify.com/help-faq/

**Comment by pjsier** [comment]
Ah I hadn't checked it against all of the pages, there might be some conflicting styles

**Comment by pjsier** [comment]
The last commit reduces the delay, fixes the logo transition (which wasn't firing at the top), and fixes the subnav top position

**Comment by james-minton** [comment]
Hmm, still getting a really long delay, relative to map / rankings

**Comment by pjsier** [comment]
I dropped the debounce time again, but we probably don't want to go much further than this

**Comment by james-minton** [comment]
Thanks for the help, Pat -- seems good to merge. @Lane when you get a chance could you have a look re: some of the remaining issues with this in #development?

**Comment by james-minton** [comment]
Also noticing that on tablet, the logo actually gets bigger on scroll, lol

**Pull request merged**
